# ------------------------------- #
# Model Settings
MODEL:
  type: UNet
  pretrained: ''
  try_load: ''
  dynamic: false

# ------------------------------- #
# Dataset Settings
DATASET:
  DIR_PATH: '/root/OroChiLab/Datasets/VOC2012'
  TRAIN:
    type: ''
    image_prefix: ''
    annotations: ''

  VAL:
    type: ''
    image_prefix: ''
    annotations: ''


  TEST:
    type: ''
    image_prefix: ''
    annotations: ''


  NUM_CLASSES: 2
  CLASSES: ''
  AUG:
    flip: true
    rot_factor: 45
    scale_factor: 0.25

DATA_PRESET:
  image_size:
    -256
    -256

# ------------------------------- #
# Train Hyperparameter Settings
WORK_DIR: ''

SNAPSHOT: 2

LOSS:
  type: 'BCELOSS'

TRAIN:
  batch_size: 128
  start_epoches: 0
  end_epoches: 200
  world_size: 1
  sync_bn: true
  fp-16: true
  optimizer: 'Adam'
  momentum: '' # Used for SGD , dafault 0.9
  weight_decay: '' # Used for SGD , dafault 0.0001
  lr: 0.001
  multistep_lr: true
  lr_factor: 0.1
  lr_step:
    - 100
    - 200

