# ------------------------------- #
# Model Settings
MODEL:
  type: UNet
  # pretrained: 'segmentation/weights/unet_carvana_scale1.0_epoch2.pth'
  pretrained: ''
  try_load: ''
  dynamic: false

# ------------------------------- #
# Dataset Settings
DATASET:
  TRAIN:
    type: 'PPHumanSeg14K'
    dataset_root: '/root/OroChiLab/Datasets/PP-HumanSeg14K'
    train_path: 'train.txt'
    aug:
      - type: Resize
        size: [192,192]
      - type: Flip
      - type: Rotation
        rot_factor: 45

  VAL:
    type: 'PPHumanSeg14K'
    dataset_root: '/root/OroChiLab/Datasets/PP-HumanSeg14K'
    val_path: 'val.txt'
    aug:
      - type: Resize
        size: [192,192]

  TEST:
    type: 'PPHumanSeg14K'
    dataset_root: '/root/OroChiLab/Datasets/PP-HumanSeg14K'
    test_path: 'test.txt'
    aug:
      - type: Resize
        size: [192,192]


  NUM_CLASSES: 2
  CLASSES: ''
  AUG:
    flip: true
    rot_factor: 45
    scale_factor: 0.25

DATA_PRESET:
  image_size:
    - 256
    - 256

# ------------------------------- #
# Train Hyperparameter Settings
WORK_DIR: ''

SNAPSHOT: 2

LOSS:
  type: 'BCELoss'

TRAIN:
  batch_size: 128
  start_epoches: 0
  end_epoches: 200
  world_size: 1
  sync_bn: true
  fp-16: true
  optimizer: 'Adam'
  momentum: '' # Used for SGD , dafault 0.9
  weight_decay: '' # Used for SGD , dafault 0.0001
  lr: 0.001
  multistep_lr: true
  lr_factor: 0.1
  lr_step:
    - 100
    - 200

